name: Pull from Remote
on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull from Remote
        run: |
          git fetch --all
          branches=$(git branch -r | grep -v '\->' | grep -v 'origin/HEAD')

          for branch in $branches; do
            branch_name=$(echo $branch | sed 's/origin\///')
            git checkout $branch_name || git checkout -b $branch_name
            git reset --hard $branch
          done

          git checkout main
